apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
        "auths": {
            "ghcr.io": {
                "username": "<your-github-username>",
                "password": "<your-github-personal-access-token>",
                "auth": "PHlvdXItZ2l0aHViLXVzZXJuYW1lPjo8eW91ci1naXRodWItcGVyc29uYWwtYWNjZXNzLXRva2VuPgo="
            }
        }
    }
