name: Build & Publish Docker

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build_publish:
    name: Build & Publish Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: github-actions
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Format Tag
        id: format-tag
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/prover
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          image_name="${IMAGE_NAME,,}"
          image_tag="${IMAGE_TAG,,}"
          echo "IMAGE_NAME=${image_name}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${image_tag}" >> $GITHUB_OUTPUT

          echo "IMAGE_NAME=${image_name}"
          echo "IMAGE_TAG=${image_tag}"

      # - name: Build Docker image
      #   env:
      #     IMAGE_NAME: ${{ steps.format-tag.outputs.IMAGE_NAME }}
      #     IMAGE_TAG: ${{ steps.format-tag.outputs.IMAGE_TAG }}
      #   run: |
      #     docker build -f docker/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
      # - name: Push Docker image
      #   env:
      #     IMAGE_NAME: ${{ steps.format-tag.outputs.IMAGE_NAME }}
      #     IMAGE_TAG: ${{ steps.format-tag.outputs.IMAGE_TAG }}
      #   run: |
      #     docker push $IMAGE_NAME:$IMAGE_TAG
