name: Build & Publish Docker

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: github-actions
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -f docker/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
      - name: Push Docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
