name: Build & Publish Helm

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  CHART_NAME: scroll-proving-sindri

jobs:
  build_publish:
    name: Build & Publish Helm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Branch Check
        if: ${{ github.event_name == 'release' && github.event.release.prerelease == false }}
        run: |
          if [[ "$GITHUB_REF_PROTECTED" == 'false' ]]; then
            echo "Releases can only be created from a protected branch"
            exit 1
          fi

      - name: Release Version
        if: ${{ github.event_name == 'release' }}
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          IS_PRERELEASE: ${{ github.event.release.prerelease }}
        run: |
          if [[ "${IS_PRERELEASE}" == "true" ]]; then
            semver_pat='^v([0-9]+)\.([0-9]+)\.([0-9]+)-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'
          else
            semver_pat='^v([0-9]+)\.([0-9]+)\.([0-9]+)$'
          fi

          if [[ ! $RELEASE_TAG =~ $semver_pat ]]; then
            echo "Invalid version: $RELEASE_TAG"
            exit 1
          fi

          release_version=${RELEASE_TAG#v}
          echo "RELEASE_VERSION=${release_version}" >> $GITHUB_ENV
          echo $release_version

      - name: Test Release Version
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          release_version="v0.0.0-${COMMIT_SHA:0:7}"
          echo "RELEASE_VERSION=${release_version}" >> $GITHUB_ENV
          echo $release_version

      - name: Chart Info
        id: chart-info
        run: |
          echo "Artifact Name: $CHART_NAME-$RELEASE_VERSION.tgz" >> $GITHUB_STEP_SUMMARY

      - name: Login to GitHub Container Registry
        env:
          USERNAME: github-actions
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          helm registry login https://ghcr.io -u $USERNAME -p $PASSWORD

      - name: Install Helm-Docs
        run: |
          curl -fsSL -o /tmp/helm-docs.deb https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.deb
          apt install /tmp/helm-docs.deb

      - name: Configure Version
        run: |
          yq e '.version = env(RELEASE_VERSION)' -i charts/${{ env.CHART_NAME }}/Chart.yaml

      - name: Build Docs
        run: |
          helm-docs -g charts/scroll-proving-sindri

      - name: Lint Chart
        run: helm lint charts/scroll-proving-sindri

      - name: Commit Changes
        run: |
          git config --global user.name "Sindri"
          git config --global user.email "sindri@noreply.com"
          git add charts/scroll-proving-sindri/Chart.yaml
          git add charts/scroll-proving-sindri/README.md
          git commit -m "Publish for $RELEASE_VERSION"

      - name: Package & Push Chart
        working-directory: charts
        env:
          ARTIFACT_NAME: ${{ env.CHART_NAME }}-$RELEASE_VERSION.tgz
          REGISTRY_NAME: ghcr.io/${{ github.repository }}/helm
        run: |
          helm package ${{ env.CHART_NAME }} --destination .
          helm push $ARTIFACT_NAME oci://$REGISTRY_NAME
          echo "Chart pushed: $ARTIFACT_NAME" >> $GITHUB_STEP_SUMMARY
